// ignore_for_file: uri_does_not_exist, undefined_identifier, undefined_function, creation_with_non_type
//
// Generated by agentx --bootstrap. Customize as needed; this file
// will not be overwritten by future agentx runs.
//
// flutter_test_config.dart is auto-discovered by `flutter test` and
// wraps every test in this package. Required by the golden-sandbox
// skill. Without it, goldens are non-deterministic across machines.
//
// Determinism strategy:
//   - CI goldens are the source of truth. They use the Ahem font and
//     skip shadow rendering by default, so output is identical on
//     every host. We keep alchemist's safe defaults.
//   - Platform goldens render real fonts and shadows; output diverges
//     across macOS / Linux / Windows. They are disabled here so a
//     Linux CI run does not fail against baselines generated on macOS.
//     Re-enable per project or per test only when verifying platform
//     rendering is the explicit goal.
//   - Per-test locale and text-scale pinning belongs inside the test
//     itself via `tester.platformDispatcher.localeTestValue` and
//     `textScaleFactorTestValue`. See section 3 of the golden-sandbox skill.

import 'dart:async';

import 'package:alchemist/alchemist.dart';

Future<void> testExecutable(FutureOr<void> Function() testMain) async {
  return AlchemistConfig.runWithConfig(
    config: const AlchemistConfig(
      platformGoldensConfig: PlatformGoldensConfig(
        enabled: false,
      ),
    ),
    run: testMain,
  );
}
