#!/usr/bin/env bash
# BOOTSTRAP.sh — one-shot dev-dependency installer for agent_rules
#
# Generated by `agentx --bootstrap`. Run once at the project root:
#   bash BOOTSTRAP.sh
#
# Idempotent: re-running is safe. Skips deps already present.
# If `flutter` is not on PATH or `pubspec.yaml` is missing, prints a
# helpful message and exits 0 (so this script can be sourced from CI
# bootstrap steps without breaking the build on non-Flutter projects).

set -euo pipefail

if ! command -v flutter >/dev/null 2>&1; then
  echo "BOOTSTRAP: flutter not found on PATH; skipping dep install." >&2
  echo "Install Flutter (https://flutter.dev) and re-run this script." >&2
  exit 0
fi

if [[ ! -f "pubspec.yaml" ]]; then
  echo "BOOTSTRAP: no pubspec.yaml in $(pwd); skipping." >&2
  echo "Run this script from the package root." >&2
  exit 0
fi

DEPS=(alchemist mocktail fake_async)

echo "BOOTSTRAP: ensuring dev_dependencies: ${DEPS[*]}"
for dep in "${DEPS[@]}"; do
  if grep -qE "^[[:space:]]*${dep}:" pubspec.yaml; then
    echo "  - ${dep}: already present, skipping"
  else
    echo "  - ${dep}: adding via flutter pub add --dev"
    flutter pub add --dev "${dep}"
  fi
done

echo "BOOTSTRAP: complete."
echo ""
echo "Next steps (handled automatically by your AI agent on first task):"
echo "  - First UI task will generate test/goldens/ baselines."
echo "  - First feature task will generate accompanying unit + widget tests."
echo ""
echo "CI workflows live at .github/workflows/{tests,goldens}.yml."
