#!/usr/bin/env bash
# scripts/release.sh
#
# Bundles bin/ and src/ into a single self-extracting
# shell script suitable for GitHub Releases (no git clone required).
#
# Usage:
#   bash scripts/release.sh [<version>]
#
# Output:
#   dist/agentx                 – the self-extracting executable
#
# Requirements: bash, tar, gzip, base64 (all standard on macOS/Linux)

set -euo pipefail

# ── Paths ──────────────────────────────────────────────────────────────
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="$REPO_ROOT/bin"
DIST_DIR="$REPO_ROOT/dist"
OUTPUT_FILE="$DIST_DIR/agentx"
VERSION="${1:-dev}"

# Clean up version string (remove 'v' prefix if present for the echo)
CLEAN_VERSION="${VERSION#v}"
echo "Building agentx v${CLEAN_VERSION} ..."

mkdir -p "$DIST_DIR"

# ── 1. Pack the bin/ and src/ directories into a base64-encoded blob ───
# We cd into the repo root so tar paths are relative to it, e.g. bin/ and src/
PAYLOAD="$(
  cd "$REPO_ROOT"
  tar -czf - \
    bin \
    src \
  | base64
)"

# ── 2. Write the self-extracting stub ─────────────────────────────────
# The stub:
#   a) decodes the base64 payload into a temp dir
#   b) makes the extracted scripts executable
#   c) execs bin/agentx.sh with the original arguments
cat > "$OUTPUT_FILE" << 'STUB_EOF'
#!/usr/bin/env bash
# agentx – self-extracting single-file executable
# Generated by scripts/release.sh – do not edit manually.
set -euo pipefail

# Decode and extract the payload into a temp directory
_TMPDIR="$(mktemp -d)"
trap 'rm -rf "$_TMPDIR"' EXIT

# Everything after the __PAYLOAD__ marker is the base64 archive
_PAYLOAD_START=$(awk '/^__PAYLOAD__$/{print NR+1; exit}' "$0")
tail -n +"$_PAYLOAD_START" "$0" | base64 --decode | tar -xzf - -C "$_TMPDIR"

# Make all extracted shell scripts executable
find "$_TMPDIR/bin" -name "*.sh" -exec chmod +x {} \;

# Hand off to agentx.sh, forwarding all arguments
exec "$_TMPDIR/bin/agentx.sh" "$@"

# ── end of stub; payload follows ──────────────────────────────────────
__PAYLOAD__
STUB_EOF

# ── 3. Append the base64 payload ──────────────────────────────────────
printf '%s\n' "$PAYLOAD" >> "$OUTPUT_FILE"

# ── 4. Make the output executable ─────────────────────────────────────
chmod +x "$OUTPUT_FILE"

echo "Done! Artifact: $OUTPUT_FILE"
echo ""
echo "Test it:"
echo "  $OUTPUT_FILE --help"
